### ISSUE TITLE
Locks even for read-only calls

### ISSUE THREAD

**Issue by bigpresh** [perlancar/perl-Unix-Passwd-File#1]
The documentation claims:

> Read-only functions like `list_users()` and `get_max_gid()` open in read-only mode. Functions that might write to the files like `add_user()` or `delete_group()` first lock `passwd.lock` file, open in read+write mode and also read the files in the first pass, then seek to the beginning and write back the files.

However, the actual implementation in `_routine()` goes straight to attempting to get a lock (opening `/etc/passwd.lock`, which a normal user will not have permissions to do).

If the behaviour was changed to match the docs, though, it'd probably be safest for the backup stuff to be done by a straightforward copy, and writing the file to be done by writing to a temp file then renaming over the top of the file to guarantee an atomic write (so a process that started reading while another process is writing to it doesn't get half a file).

**Comment by perlancar** [comment]
Sorry, missed this PR/issue (didn't receive notification from GitHub).

Commit 25edb60 accidentally introduced the bug of always locking no matter what the action is, by removing the conditional:

```
if ($args{_lock}) {
```

I've now fixed the bug.

**Comment by perlancar** [comment]
As for the atomic write issue, backup is done after the exclusive lock so as long as the other process respects the lock then it should be "safe". Then again, the lock is currently being acquired for `/etc/passwd.lock` instead of `/etc/passwd` itself, so compatibility with other programs/libraries that write to `/etc/passwd` et al is not great at the moment.

The lock should ideally be acquired for `/etc/passwd` file. But I forgot why I've locked a separate lock file, even before the switch to File::Flock::Retry.

**Comment by perlancar** [comment]
In v0.23, I'm experimentally locking all the $etc/{passwd,shadow,group,gshadow} instead of $etc/passwd.lock.
